qiniu:
  bucket: syso
  domain: syso.qiniudn.com
  ak: yRXGIzOvJBBfMOelm4O3vqasPGXj_lAuVTso4qul
  sk: ijola0yT9Gymxh7bw9ZPfQSfGZ09aHvyzWK4PRvD
  expires_in: 1576800000
redis:
  host: 127.0.0.1
  port: 6379
  queue: 0
  sidekiq_db: 1
  object_db: 2
  position: 3
elasticsearch:
  hosts:
    - localhost:9200
  log: log/development-elasticsearch.log
sms:
  log: log/development-sms.log
  url: http://gw.api.taobao.com/router/rest
  appkey: 23330920
  appsecret: a373185efbda27412395cc3bff8ba0ee
  method_str: alibaba.aliqin.fc.sms.num.send
mail:
  url: http://sendcloud.sohu.com/webapi/mail.send.json
  api_user: yiliaohj_mail
  api_key: qMgh602Vx1zeL4kf
  from: mail@yiliaohj.com
  log: log/development-mail.log